#!/bin/bash

# PulseCheck Supabase Setup Script
# Uses curl to interact with Supabase

PROJECT_REF="yfpmsaqxxfrqchkduhta"
SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmcG1zYXF4eGZycWNoa2R1aHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA4OTcxMTYsImV4cCI6MjEwNjQ3MzExNn0.81aCYKib-biNwMi9WsfWbrPtkbw_3-cqaQ4aJqx-H20"

echo "============================================================"
echo "PulseCheck Supabase Setup"
echo "============================================================"
echo "Project: $PROJECT_REF"
echo "URL: $SUPABASE_URL"
echo "============================================================"
echo ""

# Test connection
echo "🔌 Testing connection..."
RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
  -H "apikey: $ANON_KEY" \
  -H "Authorization: Bearer $ANON_KEY" \
  "$SUPABASE_URL/rest/v1/")

if [ "$RESPONSE" == "200" ]; then
  echo "✅ Connection successful!"
else
  echo "❌ Connection failed (HTTP $RESPONSE)"
  echo ""
  echo "Please check:"
  echo "  - Internet connection"
  echo "  - Project ID: $PROJECT_REF"
  echo "  - Anon key is valid"
  exit 1
fi

echo ""
echo "============================================================"
echo "⚠️  MANUAL SETUP REQUIRED"
echo "============================================================"
echo ""
echo "The anon key doesn't have permissions to create tables."
echo "You need to use the Supabase Dashboard:"
echo ""
echo "STEP 1: Create Database Tables"
echo "--------------------------------"
echo "1. Go to: https://supabase.com/dashboard/project/$PROJECT_REF/sql"
echo ""
echo "2. Click 'New Query'"
echo ""
echo "3. Copy entire contents of:"
echo "   /Users/mark/Pulse_Check/SUPABASE_SCHEMA.sql"
echo ""
echo "4. Paste into SQL Editor"
echo ""
echo "5. Click 'Run' (or press Cmd+Enter)"
echo ""
echo "6. Wait for 'Success' message"
echo ""
echo "7. Verify in Table Editor - should see 7 tables:"
echo "   ✓ user_profiles"
echo "   ✓ emergency_contacts"
echo "   ✓ sos_alerts"
echo "   ✓ location_updates"
echo "   ✓ alert_notifications"
echo "   ✓ video_recordings"
echo "   ✓ video_sharing_log"
echo ""
echo "============================================================"
echo ""
echo "STEP 2: Create Storage Bucket"
echo "--------------------------------"
echo "1. Go to: https://supabase.com/dashboard/project/$PROJECT_REF/storage/buckets"
echo ""
echo "2. Click 'Create a new bucket'"
echo ""
echo "3. Configure:"
echo "   Name: sos-videos"
echo "   Public: ❌ UNCHECK (must be private!)"
echo "   File size limit: 100 MB"
echo "   Allowed MIME types:"
echo "     - video/mp4"
echo "     - video/quicktime"
echo "     - video/mpeg"
echo "     - video/x-matroska"
echo ""
echo "4. Click 'Create bucket'"
echo ""
echo "5. Verify: bucket 'sos-videos' appears with 🔒 icon"
echo ""
echo "============================================================"
echo ""
echo "STEP 3: Build and Test App"
echo "--------------------------------"
echo "After completing Steps 1 & 2:"
echo ""
echo "cd /Users/mark/Pulse_Check"
echo "./gradlew assembleDebug"
echo "adb install -r app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "Then test:"
echo "1. Hold SOS button for 10 seconds (records 2 segments)"
echo "2. Release button (triggers countdown)"
echo "3. Check SMS for video links"
echo "4. Click link to verify video plays"
echo ""
echo "============================================================"
echo "✅ Setup guide complete!"
echo "============================================================"
echo ""
echo "Quick Links:"
echo "- SQL Editor: https://supabase.com/dashboard/project/$PROJECT_REF/sql"
echo "- Storage: https://supabase.com/dashboard/project/$PROJECT_REF/storage"
echo "- Tables: https://supabase.com/dashboard/project/$PROJECT_REF/editor"
echo ""
